name: zatiq  
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dartz: ^0.10.1
  logger: ^2.5.0
  go_router: ^15.1.2
  go_transitions: ^0.8.1
  flutter_dotenv: ^5.2.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  form_builder_validators: ^11.1.2
  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1
  solar_icon_pack: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  build_runner: ^2.4.14
  hive_ce_generator: ^1.8.2
  # dart pub run build_runner build --delete-conflicting-outputs
  flutter_lints: ^3.0.0
  rename_app: ^1.6.2 #dart run rename_app:main all="App Name"
  change_app_package_name: ^1.5.0 #dart run change_app_package_name:main com.new.package.name

flutter:

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - .env
    - assets/fonts/
    - assets/svgs/
    - assets/pngs/

  fonts:
    - family: NeueHaasDisplay
      fonts:
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayBlack.ttf
          weight: 900
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayBlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayBoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayLight.ttf
          weight: 300
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayLightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayMedium.ttf
          weight: 500
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayMediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayRoman.ttf
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayRomanItalic.ttf
          style: italic
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayThin.ttf
          weight: 100
        - asset: assets/fonts/neue-hass-grotesk/NeueHaasDisplayThinItalic.ttf
          weight: 100
          style: italic
    - family: IntegralCF
      fonts:
        - asset: assets/fonts/integral/IntegralCF-Bold.otf
          weight: 700
        - asset: assets/fonts/integral/IntegralCF-BoldOblique.otf
          weight: 700
          style: italic
        - asset: assets/fonts/integral/IntegralCF-DemiBold.otf
          weight: 600
        - asset: assets/fonts/integral/IntegralCF-DemiBoldOblique.otf
          weight: 600
          style: italic
        - asset: assets/fonts/integral/IntegralCF-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/integral/IntegralCF-ExtraBoldOblique.otf
          weight: 800
          style: italic
        - asset: assets/fonts/integral/IntegralCF-Heavy.otf
          weight: 900
        - asset: assets/fonts/integral/IntegralCF-HeavyOblique.otf
          weight: 900
          style: italic
        - asset: assets/fonts/integral/IntegralCF-Medium.otf
          weight: 500
        - asset: assets/fonts/integral/IntegralCF-MediumOblique.otf
          weight: 500
          style: italic
        - asset: assets/fonts/integral/IntegralCF-Regular.otf
          weight: 400
        - asset: assets/fonts/integral/IntegralCF-RegularOblique.otf
          weight: 400
          style: italic
  uses-material-design: true

